### ISSUE TITLE
ImageJ: repeated AutoPkgr notifications with no update/download

### ISSUE THREAD

**Issue by andrewvalentine** [autopkg/jessepeterson-recipes#8] opened 2015-03-27 16:23 UTC
Hi!

My organisation has the following AutoPkg recipe repo added to our Munki setup:

https://github.com/autopkg/jessepeterson-recipes.git

Through this, we've installed ImageJ:

$ autopkg run -v ImageJ.munki

The ImageJ recipe has then been enabled as a watched recipe in AutoPkgr, with AutoPkgr set to run once a day.

Each AutoPkgr notification informs us of the following:

**The following software is now available for testing:**

**ImageJ: 1.49**

However, no new version of ImageJ is present in our Testing catalog. The current version available in our Standard catalog is ImageJ 1.49p. We've now unchecked the recipe in AutoPkgr and no further notifications have been received. Any advice?

Thanks,

Andrew

**Comment by jessepeterson** [comment] 2015-05-28 07:20
Sorry for the delay. Yep, I get this as well. The problem is that there is no ETag or filesize provided by the web server for ImageJ. So autopkg has no way to tell if ImageJ is new or changed, unfortunately, so assumes it needs to download it again. I can try to find some time to track down if that's really true - and add some sort of local cache checking in the recipe to fake it's idempotence.

**Comment by jessepeterson** [comment] 2015-05-29 19:11
So the http://rsbweb.nih.gov/ webserver A) does not use ETags, B) does not return content size and C) while it does return a `Last-Modified` HTTP header the webserver appears to be ignoring the `If-Modified-Since` HTTP request header (which autopkg uses to tell if content has changed or not). So autopkg thinks it needs to download bits on every run. Interestingly the download link for the `il.jar` file *does* return a file size, but it's on a different webserver: http://rsb.info.nih.gov

This boils down to a problem with the webserver. You could try to petition the group to fix their webserver - maybe reaching out on their mailling list: http://rsbweb.nih.gov/ij/list.html

Because this isn't so much an issue with autopkg or this recipe, I'm going to close this issue. Do comment back if you make headway on getting in touch with them, though!

**Closed by jessepeterson** 2015-05-29 19:11 UTC

**Comment by andrewvalentine** [comment] 2015-06-08 20:38
Hi Jesse,

See below for the response I received from the webserver people on the
ImageJ mailing list. Can the AutoPkg recipe be modified to make use of this
alternative webserver?

Thanks,

Andrew

---------- Forwarded message ----------
From: Curtis Rueden <ctrueden@wisc.edu>
Date: 5 June 2015 at 20:28
Subject: Re: Webserver issue
To: IMAGEJ@list.nih.gov


Hi Andrew,

> Is anyone on this list able to advise and/or fix?

As a workaround, you could use mirror.imagej.net, which mirrors
imagej.nih.gov daily, and behaves more properly.

Regards,
Curtis

On Fri, Jun 5, 2015 at 9:48 AM, Andrew Valentine <
Andrew.Valentine@bristol.ac.uk> wrote:

> Hi there,
>
> Not sure if this the right place for this, but any advice greatly
> appreciated.
>
> My organisation uses Munki and AutoPkg, and has been using the following
> AutoPkg recipe to keep ImageJ up to date:
>
>
>
https://github.com/autopkg/jessepeterson-recipes/blob/master/NIH-RSB/ImageJ.munki.recipe
>
> This was generating error notifications via AutoPkgr. I raised this as an
> issue with the author of the recipe on GitHub:
>
>
>
https://github.com/autopkg/jessepeterson-recipes/issues/8#issuecomment-106905875
>
> The author response was:
>
> So the http://rsbweb.nih.gov/ webserver A) does not use ETags, B) does not
> > return content size and C) while it does return a Last-Modified HTTP
> > header the webserver appears to be ignoring the If-Modified-Since HTTP
> > request header (which autopkg uses to tell if content has changed or
> not).
> > So autopkg thinks it needs to download bits on every run. Interestingly
> the
> > download link for the il.jar file *does* return a file size, but it's on
> > a different webserver: http://rsb.info.nih.gov
> > This boils down to a problem with the webserver. You could try to
> petition
> > the group to fix their webserver - maybe reaching out on their mailling
> > list: http://rsbweb.nih.gov/ij/list.html
> > Because this isn't so much an issue with autopkg or this recipe, I'm
> going
> > to close this issue. Do comment back if you make headway on getting in
> > touch with them, though!
>
>
> Is anyone on this list able to advise and/or fix?
>
> Thanks,
>
> Andrew
>
> --
> ImageJ mailing list: http://imagej.nih.gov/ij/list.html
>

--
ImageJ mailing list: http://imagej.nih.gov/ij/list.html



-- 
Andrew Valentine
IT Support Officer (Zone E)
IT Services
P: 0117 3315755



-- 
Andrew Valentine
P: 07828 045095

**Comment by jessepeterson** [comment] 2015-06-08 21:20
That appears to work. The mirror.imagej.net does seem to present a proper file size. The disadvantage is that we might be a day late on new versions of ImageJ. Give it a try!
